#!/usr/bin/bash

mv /sudoers /etc/
echo lws > /etc/hostname
echo fallocate -l 2GB /swapfile
echo chmod 600 /swapfile 
echo mkswap /swapfile
echo swapon /swapfile
ln -sf /usr/share/zoneinfo/America/Tegucigalpa /etc/localtime
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
locale-gen
hwclock -w
./grub
