#!/usr/bin/bash
set -e -u

echo
echo "Discos disponibles para trabajar"
echo "Seleccionar uno: sdX"
echo 

fdisk -l | grep Dis | grep /dev/sd | cut -d "," -f1 | cut -d " " -f2,3,4 | cut -d "/" -f3
#fdisk -l | grep Dis | cut -d "," -f1
echo
# en unidad se debe escribir el nombre y direccion del disco "/dev/sdX
read unidad

tamanio=$(fdisk -l | grep $unidad | grep bytes | cut -d ',' -f 3 | cut -d ' ' -f 2)

home=$((tamanio/2))

(
# arranque del bios
# particion 1 
echo o
echo n
echo p
echo
echo
echo +1M

# Formato Bios Boot
echo t
echo 4

# EFI
# particion 2
echo n
echo p
echo
echo
echo +100M

echo t
echo 2
echo ef

#home
# particion 3
echo n 		#nueva particion
echo p 		#tipo particion
echo		#nro de particion
echo		#primer sector
echo $home	#ultimo sector

#raiz
# particion 4 
echo n
echo p
echo
echo 
echo

echo w
) | fdisk "/dev/"$unidad 

echo "======Formateando particiones ======"

mkfs.ext4 "/dev/"$unidad"4"
mkfs.ext4 "/dev/"$unidad"3"
mkfs.fat -F32 "/dev/"$unidad"2"

echo "=====Montando unidades======="


echo "/mnt montando ... "
mount "/dev/"$unidad"4" /mnt
echo "creando directorio home ..."
mkdir -p /mnt/home
echo "montando home ..."
mount "/dev/"$unidad"3" /mnt/home
echo "creando directorio EFI ..."
mkdir -p /mnt/boot/EFI
echo "montando EFI ..."
mount "/dev/"$unidad"2" /mnt/boot/EFI
echo
./paquetes
