#!/usr/bin/bash
set -e -u
cd /

# Inicio de session
pacman -S xorg-server gdm --noconfirm

# Entorno de escritorio i3
#echo "1 2 3" | pacman -S i3 --noconfirm

#Escritorio kde 
echo "all" | pacman -S gnome --noconfirm
#echo "all" | pacman -S xfce4-goodies --noconfirm

# Herramientas desarrollo
pacman -S docker docker-compose alacritty wget curl meld go git nodejs npm --noconfirm 

# Herramientas del sistema
pacman -S htop xdg-user-dirs networkmanager network-manager-applet nm-connection-editor --noconfirm 

# Herramientas i3
#pacman -S brightnessc dmenu feh picom py3status i3-gaps

# mas paquetes
#pacman -S firefox vokoscreen openssh neovim inkscape gimp libreoffice latte-dock yar cups youtube-dl tilix neofetch thunar thunar-media-tags-plugin thunar-volman filezilla ffmpeg evince --noconfirm

# AUR
# pacman -U Packages/yay-10.2.2-2-x86_64.pkg.tar.zst --noconfirm

# cargando configuracion de lightdm
#rm /etc/lightdm/lightdm.conf
#mv lightdm.conf /etc/lightdm/
#echo "background=/usr/share/backgrounds/wall1.png" >> /etc/lightdm/lightdm-gtk-greeter.conf

# configuracion para el touchpad
mv 50-synaptics.conf /etc/X11/xorg.conf.d/

#fonts
mv fonts/* /usr/share/fonts/
rm -r fonts/

#servicios
systemctl enable gdm  
systemctl enable NetworkManager
# systemctl enable bluetooth.service

# cargando paquete de iconos
#mv Luv /usr/share/icons/

# eliminados archivos importados del git arch
rm conf grub extras
rm -r Packages

# comando ves carga y configuracion
#git clone https://github.com/SolimanHub/comando_ves
#ln -s /opt/comando_ves/ves /usr/bin/ves

# recordamos el nombre de usuario 
while IFS= read -r line
do
  u="$line"
done < /opt/user
rm /opt/user
chmod 777 /user_conf
mv /user_conf /home/$u

# iniciamos como el nuevo usuario
clear
echo "===== ./user_conf ======"
su $ut
