#!/usr/bin/bash
set -e -u

loadkeys en

echo "El particionando automatico del disco es para maquinas virtuales"
echo "por lo que recomiendo hacer el particionado de discos de forma manual"
echo "para tener una referencia de como utilizar el comando fdisk"
echo "puede ver el codigo del archivo llamado 'discos'"
echo
echo "¿Desea hacer el particionado manual? [S/N]"

read respuesta

if [ $respuesta = "S" ] || [ $respuesta = "s" ] || [ $respuesta = "" ]
then
  echo "GREAT choice, once you finish execute the script ./packages"
else
  ./disks
fi

