#!/usr/bin/bash
set -e -u

cp sudoers /mnt
cp ./50-synaptics.conf /mnt
cp user_conf /mnt
cp conf /mnt
cp grub /mnt
cp ./grub_conf /mnt
cp extras /mnt
#cp lightdm.conf /mnt
cp -r Packages/mnt
#cp -r Luv /mnt
cp -r fonts/ /mnt

echo "====== ./conf ====="

arch-chroot /mnt
