#!/usr/bin/bash

cd ~
#mkdir -p .config/i3
#cd .config/i3
#curl -O https://raw.githubusercontent.com/SolimanHub/i3wn/master/config
#cd ../
#git clone https://github.com/SolimanHub/xfce4.git
#cd xfce4/
#old_user=$(grep -r dse_xeon | cut -d ":" -f1)
#sed -i "s/dse_xeon/$whoami/g" $old_user

start-pulseaudio-x11
pulseaudio --start
